import assert from 'node:assert/strict';
import {parseShadowConfig,evaluateShadowEligibility,localShadowTarget} from './config';
import {derivePriceComponents,buildShadowPlan,deriveTrustSignals} from './plan';
import {resolveShadowIdentity} from './identity';
import {extractIdentifiers,buildObservationFingerprint} from '../domain';
import {runCommerceShadowCanary} from './service';
import {WriteBudget,type CommerceShadowInput} from './contracts';
const input:CommerceShadowInput={marketplace:'AMAZON',externalId:'SHADOW-ASIN1',title:'Synthetic JBL Tune 520BT',brand:'JBL',ean:'4006381333931',price:'100',currency:'BRL',capturedAt:'2026-09-17T12:00:00.000Z',attributes:{color:'Preto',memory:'16 GB'},provenance:{sourceFlow:'offline-fixture'}};
const env={COMMERCE_SHADOW_ENABLED:'true',COMMERCE_SHADOW_MARKETPLACE:'AMAZON',COMMERCE_SHADOW_EXTERNAL_ID:'SHADOW-ASIN1',COMMERCE_SHADOW_MAX_WRITES:'1'};
async function main(){
const config=parseShadowConfig(env);
assert.deepEqual(parseShadowConfig({}),{enabled:false,marketplace:undefined,externalId:undefined,maxWrites:0,dryRun:true,requireExactIdentity:true,recordConflicts:false});
for(const bad of ['','yes','1','TRUE-ish'])assert.equal(parseShadowConfig({...env,COMMERCE_SHADOW_ENABLED:bad}).enabled,false);
assert.equal(parseShadowConfig({...env,COMMERCE_SHADOW_ENABLED:' True '}).enabled,true);
for(const bad of ['garbage','','TRUE-ish']) {assert.equal(parseShadowConfig({...env,COMMERCE_SHADOW_DRY_RUN:bad}).dryRun,true);assert.equal(parseShadowConfig({...env,COMMERCE_SHADOW_REQUIRE_EXACT_IDENTITY:bad}).requireExactIdentity,true);}
for(const bad of ['-1','1.5','01','1e3','garbage','9007199254740992'])assert.equal(parseShadowConfig({...env,COMMERCE_SHADOW_MAX_WRITES:bad}).maxWrites,0);
for(const bad of ['*','SHADOW-*','SHADOW-ASIN1,other'])assert.equal(parseShadowConfig({...env,COMMERCE_SHADOW_EXTERNAL_ID:bad}).externalId,undefined);
assert.equal(evaluateShadowEligibility(input,{...config,enabled:false}).reason,'SHADOW_DISABLED');
assert.equal(evaluateShadowEligibility({...input,externalId:''},config).reason,'MISSING_EXTERNAL_ID');
assert.equal(evaluateShadowEligibility({...input,price:-1},config).reason,'INVALID_INPUT');
assert.equal(evaluateShadowEligibility({...input,marketplace:'SHOPEE'},config).reason,'MARKETPLACE_NOT_ALLOWED');
assert.equal(evaluateShadowEligibility({...input,externalId:'SHADOW-ASIN10'},config).reason,'EXTERNAL_ID_NOT_ALLOWED');
assert.equal(evaluateShadowEligibility(input,{...config,maxWrites:0}).reason,'WRITE_BUDGET_ZERO');
assert.equal(evaluateShadowEligibility(input,config).reason,'DRY_RUN');
assert.equal(evaluateShadowEligibility(input,{...config,dryRun:false},{writePhase:true,identity:{status:'HIGH',confidence:'HIGH',productId:null,candidateIds:['p'],method:'model'}}).reason,'IDENTITY_NOT_EXACT');
assert.equal(evaluateShadowEligibility(input,{...config,dryRun:false}).reason,'RAW_NOT_REQUIRED');
assert.equal(evaluateShadowEligibility(input,{...config,dryRun:false,requireExactIdentity:false},{writePhase:true,identity:{status:'HIGH',confidence:'HIGH',productId:null,candidateIds:['p'],method:'model'}}).reason,'IDENTITY_NOT_EXACT');
assert.equal(localShadowTarget('postgresql://127.0.0.1:55432/ofertano_50ag2_shadow',undefined),'LOCAL_TARGET_REQUIRED');
assert.equal(localShadowTarget('postgresql://127.0.0.1:55433/ofertano_50ag2_shadow','production'),'PRODUCTION_FORBIDDEN');
assert.equal(localShadowTarget('postgresql://127.0.0.1:55433/ofertano_50ag2_shadow?host=remote.example',undefined),'LOCAL_TARGET_REQUIRED');
const row={id:'i',productId:'p',type:'EAN',value:'4006381333931',normalizedValue:'4006381333931',marketplace:null,brandScope:null};
const reader=(rows:unknown[],offer:null|{productId:string}=null)=>({productIdentifier:{findMany:async()=>rows},marketplaceOffer:{findUnique:async()=>offer},product:{findUnique:async()=>({brand:'JBL'})}}) as unknown as Parameters<typeof resolveShadowIdentity>[2];
assert.equal((await resolveShadowIdentity(input,extractIdentifiers(input),reader([row]))).status,'EXACT');
assert.equal((await resolveShadowIdentity(input,extractIdentifiers(input),reader([row,{...row,productId:'q'}]))).status,'CONFLICT');
assert.equal((await resolveShadowIdentity(input,extractIdentifiers(input),reader([], {productId:'p'}))).status,'EXACT');
assert.equal((await resolveShadowIdentity({...input,ean:undefined},extractIdentifiers({...input,ean:undefined}),reader([]))).status,'UNRESOLVED');
const mpn={...row,type:'MPN',value:'M-1',normalizedValue:'M-1',brandScope:'jbl'};
assert.equal((await resolveShadowIdentity({...input,ean:undefined,mpn:'M-1'},extractIdentifiers({...input,ean:undefined,mpn:'M-1'}),reader([mpn]))).status,'EXACT');
const weak={...row,type:'MODEL',value:'TUNE 520BT',normalizedValue:'TUNE 520BT',brandScope:'jbl'};
const weakReader={productIdentifier:{findMany:async(args:{where:{type?:string}})=>args.where.type==='MODEL'?[weak]:[]},marketplaceOffer:{findUnique:async()=>null}} as unknown as Parameters<typeof resolveShadowIdentity>[2];
const weakInput={...input,ean:undefined,modelNumber:'Tune 520BT'};
assert.equal((await resolveShadowIdentity(weakInput,extractIdentifiers(weakInput),weakReader)).status,'HIGH');
assert.deepEqual(derivePriceComponents(input).map(c=>c.type),['SALE_PRICE']);
assert.deepEqual(derivePriceComponents({...input,oldPrice:'120'}).map(c=>c.type),['SALE_PRICE']);
const rich={...input,oldPrice:'120',pricing:{oldPriceIsListPrice:true,shipping:0,coupon:{amount:5,eligible:true},pix:{amount:5,eligible:true},membership:{amount:80,eligible:false},installment:{total:120,count:12,complete:true}}};
assert.deepEqual(derivePriceComponents(rich).map(c=>c.type),['SALE_PRICE','LIST_PRICE','SHIPPING','COUPON','PIX_DISCOUNT','MEMBERSHIP_PRICE','INSTALLMENT_TOTAL']);
const identity={status:'EXACT' as const,confidence:'EXACT' as const,productId:'p',candidateIds:['p'],method:'validated-gtin'};
const plan=buildShadowPlan(input,identity,true);
assert.equal(plan.priceTruth.state,'PARTIAL');assert.ok(plan.variant);assert.equal(plan.observation.rawListingId,null);
assert.equal(buildShadowPlan({...input,attributes:{}},identity,true).variant,null);
assert.equal(buildShadowPlan({...input,attributes:{color:'a',cor:'b'}},identity,true).variant,null);
assert.equal(buildShadowPlan(input,identity,false).variant,null);
assert.equal(buildShadowPlan({...input,price:null},identity,true).priceTruth.state,'UNKNOWN');
assert.ok(deriveTrustSignals(input,identity,plan.priceTruth).every(s=>!['TRUST_SCORE','SAFE_BUY','GOOD_SELLER','BEST_OFFER'].includes(s.signalType)));
assert.equal(buildObservationFingerprint({...input,components:plan.observation.components}),plan.observation.fingerprint);
assert.equal(buildShadowPlan({...input,attributes:{memory:'16 GB',color:'Preto'}},identity,true).observation.fingerprint,plan.observation.fingerprint);
assert.notEqual(buildShadowPlan({...input,attributes:{memory:'32 GB',color:'Preto'}},identity,true).observation.fingerprint,plan.observation.fingerprint);
const never=async()=>{throw Error('OFF touched DB');};
assert.equal((await runCommerceShadowCanary(input,{env:{},getClient:never,log:()=>{}})).status,'BLOCKED');
assert.equal((await runCommerceShadowCanary(input,{env:{...env,COMMERCE_SHADOW_MAX_WRITES:'0'},getClient:never,log:()=>{}})).reason,'WRITE_BUDGET_ZERO');
const budget=new WriteBudget();const reserve=budget.reserve(1)!;assert.equal(budget.reserve(1),null);reserve();assert.equal(budget.remaining(1),1);budget.commit(budget.reserve(1)!);assert.equal(budget.remaining(1),0);
console.log('SHADOW_PURE_GATES_IDENTITY_PRICE_TRUST=PASS');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
